# Generated by Django 5.0.7 on 2024-07-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='flow_rate',
            new_name='flowRate',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='ph_value',
            new_name='pHValue',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='soil_moisture',
            new_name='soilMoisture',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='water_level',
            new_name='waterLevel',
        ),
    ]
